[build]
rustc-wrapper = ".cargo/bin/sccache"

[target.x86_64-unknown-linux-gnu]
linker = "/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/bin/mold"]

[source.panamax-sparse]
registry = "sparse+http://localhost:27428/index/"

[source.crates-io]
replace-with = "panamax-sparse"

