[default_config]
version = "0.10.0"
assembler = "gas"
instruction_set = "riscv"

[default_config.opts]
compiler = "riscv64-linux-gnu-gcc"
compile_flags_txt = []
diagnostics = true
default_diagnostics = false
